// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0

package envsqlc

import (
	"database/sql"
)

type Env struct {
	ID         int64
	Name       string
	Comment    sql.NullString
	CreateTime string
	UpdateTime string
}
