version: "2"
linters:
  enable:
    - exhaustive
    - exhaustruct
    - gochecknoglobals
    - gochecknoinits
    - nonamedreturns
    - paralleltest
    - predeclared
  settings:
    paralleltest:
      ignore-missing: false
      ignore-missing-subtests: true
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    paths:
      - third_party$
      - builtin$
      - examples$
formatters:
  enable:
    - gofmt
    - goimports
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
