// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0
// source: env_var.sql

package sqlcgen

import (
	"context"
)

const envVarCreate = `-- name: EnvVarCreate :exec
INSERT INTO env_var(
    env_id, name, comment, create_time, update_time, value
) VALUES (
    ?     , ?   , ?      , ?          , ?          , ?
)
`

type EnvVarCreateParams struct {
	EnvID      int64
	Name       string
	Comment    string
	CreateTime string
	UpdateTime string
	Value      string
}

func (q *Queries) EnvVarCreate(ctx context.Context, arg EnvVarCreateParams) error {
	_, err := q.db.ExecContext(ctx, envVarCreate,
		arg.EnvID,
		arg.Name,
		arg.Comment,
		arg.CreateTime,
		arg.UpdateTime,
		arg.Value,
	)
	return err
}

const envVarDelete = `-- name: EnvVarDelete :exec
DELETE FROM env_var WHERE env_id = ? AND name = ?
`

type EnvVarDeleteParams struct {
	EnvID int64
	Name  string
}

func (q *Queries) EnvVarDelete(ctx context.Context, arg EnvVarDeleteParams) error {
	_, err := q.db.ExecContext(ctx, envVarDelete, arg.EnvID, arg.Name)
	return err
}

const envVarFindByID = `-- name: EnvVarFindByID :one
SELECT env.name AS env_name, env_var.env_var_id, env_var.env_id, env_var.name, env_var.comment, env_var.create_time, env_var.update_time, env_var.value
FROM env_var
JOIN env ON env_var.env_id = env.env_id
WHERE env_var.env_var_id = ?
`

type EnvVarFindByIDRow struct {
	EnvName    string
	EnvVarID   int64
	EnvID      int64
	Name       string
	Comment    string
	CreateTime string
	UpdateTime string
	Value      string
}

func (q *Queries) EnvVarFindByID(ctx context.Context, envVarID int64) (EnvVarFindByIDRow, error) {
	row := q.db.QueryRowContext(ctx, envVarFindByID, envVarID)
	var i EnvVarFindByIDRow
	err := row.Scan(
		&i.EnvName,
		&i.EnvVarID,
		&i.EnvID,
		&i.Name,
		&i.Comment,
		&i.CreateTime,
		&i.UpdateTime,
		&i.Value,
	)
	return i, err
}

const envVarFindID = `-- name: EnvVarFindID :one
SELECT env_var_id FROM env_var WHERE env_id = ? AND name = ?
`

type EnvVarFindIDParams struct {
	EnvID int64
	Name  string
}

func (q *Queries) EnvVarFindID(ctx context.Context, arg EnvVarFindIDParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, envVarFindID, arg.EnvID, arg.Name)
	var env_var_id int64
	err := row.Scan(&env_var_id)
	return env_var_id, err
}

const envVarList = `-- name: EnvVarList :many
SELECT env_var_id, env_id, name, comment, create_time, update_time, value FROM env_var
WHERE env_id = ?
ORDER BY name ASC
`

func (q *Queries) EnvVarList(ctx context.Context, envID int64) ([]EnvVar, error) {
	rows, err := q.db.QueryContext(ctx, envVarList, envID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []EnvVar
	for rows.Next() {
		var i EnvVar
		if err := rows.Scan(
			&i.EnvVarID,
			&i.EnvID,
			&i.Name,
			&i.Comment,
			&i.CreateTime,
			&i.UpdateTime,
			&i.Value,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const envVarShow = `-- name: EnvVarShow :one
SELECT env_var_id, env_id, name, comment, create_time, update_time, value
FROM env_var
WHERE env_id = ? AND name = ?
`

type EnvVarShowParams struct {
	EnvID int64
	Name  string
}

func (q *Queries) EnvVarShow(ctx context.Context, arg EnvVarShowParams) (EnvVar, error) {
	row := q.db.QueryRowContext(ctx, envVarShow, arg.EnvID, arg.Name)
	var i EnvVar
	err := row.Scan(
		&i.EnvVarID,
		&i.EnvID,
		&i.Name,
		&i.Comment,
		&i.CreateTime,
		&i.UpdateTime,
		&i.Value,
	)
	return i, err
}

const envVarUpdate = `-- name: EnvVarUpdate :exec
UPDATE env_var SET
    env_id = COALESCE(?1, env_id),
    name = COALESCE(?2, name),
    comment = COALESCE(?3, comment),
    create_time = COALESCE(?4, create_time),
    update_time = COALESCE(?5, update_time),
    value = COALESCE(?6, value)
WHERE env_var_id = ?7
`

type EnvVarUpdateParams struct {
	EnvID      *int64
	Name       *string
	Comment    *string
	CreateTime *string
	UpdateTime *string
	Value      *string
	EnvVarID   int64
}

func (q *Queries) EnvVarUpdate(ctx context.Context, arg EnvVarUpdateParams) error {
	_, err := q.db.ExecContext(ctx, envVarUpdate,
		arg.EnvID,
		arg.Name,
		arg.Comment,
		arg.CreateTime,
		arg.UpdateTime,
		arg.Value,
		arg.EnvVarID,
	)
	return err
}
