// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0
// source: envsqlc.sql

package sqlcgen

import (
	"context"
	"database/sql"
)

const createEnv = `-- name: CreateEnv :one
INSERT INTO env (
    name, comment, create_time, update_time
) VALUES (
    ?   , ?      , ?          , ?
)
RETURNING name, comment, create_time, update_time
`

type CreateEnvParams struct {
	Name       string
	Comment    sql.NullString
	CreateTime string
	UpdateTime string
}

type CreateEnvRow struct {
	Name       string
	Comment    sql.NullString
	CreateTime string
	UpdateTime string
}

func (q *Queries) CreateEnv(ctx context.Context, arg CreateEnvParams) (CreateEnvRow, error) {
	row := q.db.QueryRowContext(ctx, createEnv,
		arg.Name,
		arg.Comment,
		arg.CreateTime,
		arg.UpdateTime,
	)
	var i CreateEnvRow
	err := row.Scan(
		&i.Name,
		&i.Comment,
		&i.CreateTime,
		&i.UpdateTime,
	)
	return i, err
}

const createKeyringEntry = `-- name: CreateKeyringEntry :exec
INSERT INTO keyring_entry(
    name, comment, create_time, update_time
) VALUES (
    ?   , ?      , ?          , ?
)
`

type CreateKeyringEntryParams struct {
	Name       string
	Comment    sql.NullString
	CreateTime string
	UpdateTime string
}

func (q *Queries) CreateKeyringEntry(ctx context.Context, arg CreateKeyringEntryParams) error {
	_, err := q.db.ExecContext(ctx, createKeyringEntry,
		arg.Name,
		arg.Comment,
		arg.CreateTime,
		arg.UpdateTime,
	)
	return err
}

const createLocalEnvVar = `-- name: CreateLocalEnvVar :exec
INSERT INTO env_var_local(
    env_id, name, comment, create_time, update_time, value
) VALUES (
    ?     , ?   , ?      , ?          , ?          , ?
)
`

type CreateLocalEnvVarParams struct {
	EnvID      int64
	Name       string
	Comment    sql.NullString
	CreateTime string
	UpdateTime string
	Value      string
}

func (q *Queries) CreateLocalEnvVar(ctx context.Context, arg CreateLocalEnvVarParams) error {
	_, err := q.db.ExecContext(ctx, createLocalEnvVar,
		arg.EnvID,
		arg.Name,
		arg.Comment,
		arg.CreateTime,
		arg.UpdateTime,
		arg.Value,
	)
	return err
}

const findEnvID = `-- name: FindEnvID :one
SELECT id FROM env WHERE name = ?
`

func (q *Queries) FindEnvID(ctx context.Context, name string) (int64, error) {
	row := q.db.QueryRowContext(ctx, findEnvID, name)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const listLocalEnvVars = `-- name: ListLocalEnvVars :many
SELECT id, env_id, name, comment, create_time, update_time, value FROM env_var_local
WHERE env_id = ?
ORDER BY name ASC
`

func (q *Queries) ListLocalEnvVars(ctx context.Context, envID int64) ([]EnvVarLocal, error) {
	rows, err := q.db.QueryContext(ctx, listLocalEnvVars, envID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []EnvVarLocal
	for rows.Next() {
		var i EnvVarLocal
		if err := rows.Scan(
			&i.ID,
			&i.EnvID,
			&i.Name,
			&i.Comment,
			&i.CreateTime,
			&i.UpdateTime,
			&i.Value,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateEnv = `-- name: UpdateEnv :exec
UPDATE env SET
    name = COALESCE(?1, name),
    comment = COALESCE(?2, comment),
    create_time = COALESCE(?3, create_time),
    update_time = COALESCE(?4, update_time)
WHERE name = ?5
`

type UpdateEnvParams struct {
	NewName    sql.NullString
	Comment    sql.NullString
	CreateTime sql.NullString
	UpdateTime sql.NullString
	Name       string
}

// See https://docs.sqlc.dev/en/latest/howto/named_parameters.html#nullable-parameters
func (q *Queries) UpdateEnv(ctx context.Context, arg UpdateEnvParams) error {
	_, err := q.db.ExecContext(ctx, updateEnv,
		arg.NewName,
		arg.Comment,
		arg.CreateTime,
		arg.UpdateTime,
		arg.Name,
	)
	return err
}
