// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0
// source: keyring_entry.sql

package sqlcgen

import (
	"context"
)

const createKeyringEntry = `-- name: CreateKeyringEntry :exec
INSERT INTO keyring_entry(
    name, comment, create_time, update_time
) VALUES (
    ?   , ?      , ?          , ?
)
`

type CreateKeyringEntryParams struct {
	Name       string
	Comment    string
	CreateTime string
	UpdateTime string
}

func (q *Queries) CreateKeyringEntry(ctx context.Context, arg CreateKeyringEntryParams) error {
	_, err := q.db.ExecContext(ctx, createKeyringEntry,
		arg.Name,
		arg.Comment,
		arg.CreateTime,
		arg.UpdateTime,
	)
	return err
}

const findKeyringID = `-- name: FindKeyringID :one
SELECT id from keyring_entry WHERE name = ?
`

func (q *Queries) FindKeyringID(ctx context.Context, name string) (int64, error) {
	row := q.db.QueryRowContext(ctx, findKeyringID, name)
	var id int64
	err := row.Scan(&id)
	return id, err
}
