// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0
// source: keyring_entry.sql

package sqlcgen

import (
	"context"
)

const keyringEntryCreate = `-- name: KeyringEntryCreate :exec
INSERT INTO keyring_entry(
    name, comment, create_time, update_time
) VALUES (
    ?   , ?      , ?          , ?
)
`

type KeyringEntryCreateParams struct {
	Name       string
	Comment    string
	CreateTime string
	UpdateTime string
}

func (q *Queries) KeyringEntryCreate(ctx context.Context, arg KeyringEntryCreateParams) error {
	_, err := q.db.ExecContext(ctx, keyringEntryCreate,
		arg.Name,
		arg.Comment,
		arg.CreateTime,
		arg.UpdateTime,
	)
	return err
}

const keyringEntryFindID = `-- name: KeyringEntryFindID :one
SELECT id from keyring_entry WHERE name = ?
`

func (q *Queries) KeyringEntryFindID(ctx context.Context, name string) (int64, error) {
	row := q.db.QueryRowContext(ctx, keyringEntryFindID, name)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const keyringEntryShow = `-- name: KeyringEntryShow :one
SELECT id, name, comment, create_time, update_time FROM keyring_entry WHERE name = ?
`

func (q *Queries) KeyringEntryShow(ctx context.Context, name string) (KeyringEntry, error) {
	row := q.db.QueryRowContext(ctx, keyringEntryShow, name)
	var i KeyringEntry
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Comment,
		&i.CreateTime,
		&i.UpdateTime,
	)
	return i, err
}
