// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0

package sqlcgen

import (
	"database/sql"
)

type Env struct {
	ID         int64
	Name       string
	Comment    sql.NullString
	CreateTime string
	UpdateTime string
}

type EnvVarLocal struct {
	ID         int64
	EnvID      int64
	Name       string
	Comment    sql.NullString
	CreateTime string
	UpdateTime string
	Value      string
}

type EnvVarUniqueName struct {
	ID    int64
	EnvID int64
	Name  string
}

type KeyringEntry struct {
	ID         int64
	Name       string
	Comment    sql.NullString
	CreateTime string
	UpdateTime string
}
